package com.jesper.mapper;

import com.jesper.model.Delivery;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface DeliveryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kuaidi100_delivery
     *
     * @mbggenerated Sat Mar 31 09:37:10 CST 2018
     */
    int deleteByPrimaryKey(Integer id);
    int deleteByDeliveryName(String deliveryName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kuaidi100_delivery
     *
     * @mbggenerated Sat Mar 31 09:37:10 CST 2018
     */
    int insert(Delivery record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kuaidi100_delivery
     *
     * @mbggenerated Sat Mar 31 09:37:10 CST 2018
     */
    Delivery selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kuaidi100_delivery
     *
     * @mbggenerated Sat Mar 31 09:37:10 CST 2018
     */
    List<Delivery> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kuaidi100_delivery
     *
     * @mbggenerated Sat Mar 31 09:37:10 CST 2018
     */
    int updateByPrimaryKey(Delivery record);

    Delivery selectByName(String name);
}