package com.jesper.mapper;

import com.jesper.model.OrderShipping;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;


@Mapper
public interface OrderShippingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order_shipping
     *
     * @mbggenerated Sun Mar 25 11:38:19 CST 2018
     */
    int deleteByPrimaryKey(String orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order_shipping
     *
     * @mbggenerated Sun Mar 25 11:38:19 CST 2018
     */
    int insert(OrderShipping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order_shipping
     *
     * @mbggenerated Sun Mar 25 11:38:19 CST 2018
     */
    OrderShipping selectByPrimaryKey(String orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order_shipping
     *
     * @mbggenerated Sun Mar 25 11:38:19 CST 2018
     */
    List<OrderShipping> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order_shipping
     *
     * @mbggenerated Sun Mar 25 11:38:19 CST 2018
     */
    int updateByPrimaryKey(OrderShipping record);
}