package com.jesper.mapper;

import com.jesper.model.Month;
import com.jesper.model.Order;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface OrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order
     *
     * @mbggenerated Sun Mar 25 11:29:28 CST 2018
     */
    int deleteByPrimaryKey(String orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order
     *
     * @mbggenerated Sun Mar 25 11:29:28 CST 2018
     */
    int insert(Order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order
     *
     * @mbggenerated Sun Mar 25 11:29:28 CST 2018
     */
    Order selectByPrimaryKey(String orderId);



    List<Order> list(Order order);

    List<Order> listRefund(Order order);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order
     *
     * @mbggenerated Sun Mar 25 11:29:28 CST 2018
     */
    List<Order> selectAll();

    int selectCurOrderNum();
    int selectLastOrderNum();

    long selectCurPayment();
    long selectLastPayment();

    int selectCurRefundOrder();
    int selectLastRefundOrder();

    int selectDayOrderSum(Order order);
    int selectDayOrderNum(Order order);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order
     *
     * @mbggenerated Sun Mar 25 11:29:28 CST 2018
     */
    int updateByPrimaryKey(Order record);
}